### ISSUE TITLE
Is the HeaderPropagationValues safe to use when injected in controller?

### ISSUE THREAD

**Issue by Mubashwer** [alefranz/HeaderPropagation#11]
I need to access a Correlation ID that is fetched from the request header or is generated.

Since `HeaderPropagationValues` uses AsyncLocals to store the header values and that there is a bug which causes `AsyncLocal`s to bleed across requests, is it safe to use  `HeaderPropagationValues` when injected in a controller?

**Comment by alefranz** [comment]
Yes, it is safe to use it.
Version [3.0.2](https://github.com/alefranz/HeaderPropagation/releases/tag/3.0.2) includes a workaround to avoid that issue, so no matter in which position of the pipeline you add the middleware, you will not be affected.

**Comment by Mubashwer** [comment]
Thanks!
